sed -i'.backup' -e 's/coating/f49/g' obsf_draft.cl
sed -i'.backup' -e 's/coat/f47/g' obsf_draft.cl
sed -i'.backup' -e 's/normal/f46/g' obsf_draft.cl
sed -i'.backup' -e 's/color/f45/g' obsf_draft.cl
sed -i'.backup' -e 's/result/f44/g' obsf_draft.cl
sed -i'.backup' -e 's/material/f43/g' obsf_draft.cl
sed -i'.backup' -e 's/triangle/f42/g' obsf_draft.cl
sed -i'.backup' -e 's/tri_/fzefq42/g' obsf_draft.cl
sed -i'.backup' -e 's/vertex/f41/g' obsf_draft.cl
sed -i'.backup' -e 's/TREE/f40/g' obsf_draft.cl
sed -i'.backup' -e 's/LEAF/f39/g' obsf_draft.cl
sed -i'.backup' -e 's/FLAG/f38/g' obsf_draft.cl
sed -i'.backup' -e 's/MASK/f37/g' obsf_draft.cl
sed -i'.backup' -e 's/DOUBLE/f36/g' obsf_draft.cl
sed -i'.backup' -e 's/SIDED/f35/g' obsf_draft.cl
sed -i'.backup' -e 's/ROUGHNESS/f34/g' obsf_draft.cl
sed -i'.backup' -e 's/roughness/f33/g' obsf_draft.cl
sed -i'.backup' -e 's/NORMAL_/f32/g' obsf_draft.cl
sed -i'.backup' -e 's/COATING/f31/g' obsf_draft.cl
sed -i'.backup' -e 's/MICRO/f30/g' obsf_draft.cl
sed -i'.backup' -e 's/JITTER/f29/g' obsf_draft.cl
sed -i'.backup' -e 's/CORRELATION/f28/g' obsf_draft.cl
sed -i'.backup' -e 's/FACTOR/f27/g' obsf_draft.cl
sed -i'.backup' -e 's/NODE/f26/g' obsf_draft.cl
sed -i'.backup' -e 's/TEST/f25/g' obsf_draft.cl
sed -i'.backup' -e 's/RIGHT/f24/g' obsf_draft.cl
sed -i'.backup' -e 's/LEFT/f23/g' obsf_draft.cl
sed -i'.backup' -e 's/NONE/f22/g' obsf_draft.cl
sed -i'.backup' -e 's/STATE/f21/g' obsf_draft.cl
sed -i'.backup' -e 's/ENVIRONMENT/f20/g' obsf_draft.cl
sed -i'.backup' -e 's/EMISSIVE/f19/g' obsf_draft.cl
sed -i'.backup' -e 's/DIFFUSE/f18/g' obsf_draft.cl
sed -i'.backup' -e 's/DIELECTRIC/f17/g' obsf_draft.cl
sed -i'.backup' -e 's/CONDUCTOR/f16/g' obsf_draft.cl
sed -i'.backup' -e 's/SECONDARY/f15/g' obsf_draft.cl
sed -i'.backup' -e 's/END/f14/g' obsf_draft.cl
sed -i'.backup' -e 's/ORIGIN/f13/g' obsf_draft.cl
sed -i'.backup' -e 's/DIR/f12/g' obsf_draft.cl
sed -i'.backup' -e 's/_X/f11/g' obsf_draft.cl
sed -i'.backup' -e 's/_Y/f10/g' obsf_draft.cl
sed -i'.backup' -e 's/_Z/f09/g' obsf_draft.cl
sed -i'.backup' -e 's/MAP/f08/g' obsf_draft.cl
sed -i'.backup' -e 's/TRI/f07/g' obsf_draft.cl
sed -i'.backup' -e 's/NORMAL_/g49_/g' obsf_draft.cl
sed -i'.backup' -e 's/SUN/g47/g' obsf_draft.cl
sed -i'.backup' -e 's/COS/g46/g' obsf_draft.cl
sed -i'.backup' -e 's/THETA/g45/g' obsf_draft.cl
sed -i'.backup' -e 's/COLOR/g44/g' obsf_draft.cl
sed -i'.backup' -e 's/HIT/g43/g' obsf_draft.cl
sed -i'.backup' -e 's/BOTH/g42/g' obsf_draft.cl
sed -i'.backup' -e 's/ray/g41/g' obsf_draft.cl
sed -i'.backup' -e 's/_count/_g40/g' obsf_draft.cl
sed -i'.backup' -e 's/_state/_g39/g' obsf_draft.cl
sed -i'.backup' -e 's/global_id /g38 /g' obsf_draft.cl
sed -i'.backup' -e 's/ global_id/ g38/g' obsf_draft.cl
sed -i'.backup' -e 's/(global_id/(g38/g' obsf_draft.cl
sed -i'.backup' -e 's/RS_/g37/g' obsf_draft.cl
sed -i'.backup' -e 's/d_i /g36 /g' obsf_draft.cl
sed -i'.backup' -e 's/d_o /g35 /g' obsf_draft.cl
sed -i'.backup' -e 's/ld_i /g34 /g' obsf_draft.cl
sed -i'.backup' -e 's/ld_o /g33 /g' obsf_draft.cl
sed -i'.backup' -e 's/intensity/g32/g' obsf_draft.cl
sed -i'.backup' -e 's/sky/g31/g' obsf_draft.cl
sed -i'.backup' -e 's/table/g30/g' obsf_draft.cl
sed -i'.backup' -e 's/delta/g29/g' obsf_draft.cl
sed -i'.backup' -e 's/brdf/g28/g' obsf_draft.cl
sed -i'.backup' -e 's/pdf/g27/g' obsf_draft.cl
sed -i'.backup' -e 's/mis_/g26_/g' obsf_draft.cl
sed -i'.backup' -e 's/weight/g25/g' obsf_draft.cl
sed -i'.backup' -e 's/MIS/g24/g' obsf_draft.cl
sed -i'.backup' -e 's/horizon/g23/g' obsf_draft.cl
sed -i'.backup' -e 's/INDEX/y49_/g' obsf_draft.cl
sed -i'.backup' -e 's/THROUGHPUT/y47/g' obsf_draft.cl
sed -i'.backup' -e 's/DISTANCE/y99/g' obsf_draft.cl
sed -i'.backup' -e 's/TRAIL/y43/g' obsf_draft.cl
sed -i'.backup' -e 's/BRDF/y42/g' obsf_draft.cl
sed -i'.backup' -e 's/PDF/y41/g' obsf_draft.cl
sed -i'.backup' -e 's/EPSILON/y40/g' obsf_draft.cl
sed -i'.backup' -e 's/PI/y39/g' obsf_draft.cl
sed -i'.backup' -e 's/TAU/y38/g' obsf_draft.cl
sed -i'.backup' -e 's/INV/y00/g' obsf_draft.cl
sed -i'.backup' -e 's/Node/x49_/g' obsf_draft.cl
sed -i'.backup' -e 's/Material/x48_/g' obsf_draft.cl
sed -i'.backup' -e 's/Triangle/x47_/g' obsf_draft.cl
sed -i'.backup' -e 's/Device/x46_/g' obsf_draft.cl
sed -i'.backup' -e 's/Camera/x99/g' obsf_draft.cl
sed -i'.backup' -e 's/pixel/x43/g' obsf_draft.cl
sed -i'.backup' -e 's/image_plane_distance/x42/g' obsf_draft.cl
sed -i'.backup' -e 's/root/x41/g' obsf_draft.cl
sed -i'.backup' -e 's/pixel/x40/g' obsf_draft.cl
sed -i'.backup' -e 's/transform/x39/g' obsf_draft.cl
sed -i'.backup' -e 's/focal/x38/g' obsf_draft.cl
sed -i'.backup' -e 's/depth/x00/g' obsf_draft.cl
sed -i'.backup' -e 's/map/z49_/g' obsf_draft.cl
sed -i'.backup' -e 's/flags/z48_/g' obsf_draft.cl
sed -i'.backup' -e 's/bounds/z47_/g' obsf_draft.cl
sed -i'.backup' -e 's/scale/z46_/g' obsf_draft.cl
sed -i'.backup' -e 's/brightness/z99/g' obsf_draft.cl
sed -i'.backup' -e 's/alpha/z43/g' obsf_draft.cl
sed -i'.backup' -e 's/padding/z42/g' obsf_draft.cl
sed -i'.backup' -e 's/uvs/z41/g' obsf_draft.cl
sed -i'.backup' -e 's/edges/z40/g' obsf_draft.cl
sed -i'.backup' -e 's/surface/z39/g' obsf_draft.cl
sed -i'.backup' -e 's/PRNG/z38/g' obsf_draft.cl
sed -i'.backup' -e 's/hash/z00/g' obsf_draft.cl
sed -i'.backup' -e 's/inverse/U49_/g' obsf_draft.cl
sed -i'.backup' -e 's/strength/U48_/g' obsf_draft.cl
sed -i'.backup' -e 's/SEED/U47_/g' obsf_draft.cl
sed -i'.backup' -e 's/TRANSFORM/U46_/g' obsf_draft.cl
sed -i'.backup' -e 's/DOT/U99/g' obsf_draft.cl
sed -i'.backup' -e 's/NORMALIZE(/U43(/g' obsf_draft.cl
sed -i'.backup' -e 's/inv_len/U42/g' obsf_draft.cl
sed -i'.backup' -e 's/D_I/U41/g' obsf_draft.cl
sed -i'.backup' -e 's/FLIP/U40/g' obsf_draft.cl
sed -i'.backup' -e 's/sd_i/U39/g' obsf_draft.cl
sed -i'.backup' -e 's/theta/U38/g' obsf_draft.cl
sed -i'.backup' -e 's/cos_/U00/g' obsf_draft.cl
sed -i'.backup' -e 's/phi/Z49_/g' obsf_draft.cl
sed -i'.backup' -e 's/sin_/Z48_/g' obsf_draft.cl
sed -i'.backup' -e 's/cos_/Z47_/g' obsf_draft.cl
sed -i'.backup' -e 's/proj_area/Z46_/g' obsf_draft.cl
sed -i'.backup' -e 's/slope/Z99/g' obsf_draft.cl
sed -i'.backup' -e 's/SMITH_G1(/Z43(/g' obsf_draft.cl
sed -i'.backup' -e 's/G1/Z42/g' obsf_draft.cl
sed -i'.backup' -e 's/lambda/Z41/g' obsf_draft.cl
sed -i'.backup' -e 's/FRESNEL/Z40/g' obsf_draft.cl
sed -i'.backup' -e 's/IOR/Z39/g' obsf_draft.cl
sed -i'.backup' -e 's/temp/Z38/g' obsf_draft.cl
sed -i'.backup' -e 's/BASIS/Z00/g' obsf_draft.cl
sed -i'.backup' -e 's/GGX/J49_/g' obsf_draft.cl
sed -i'.backup' -e 's/fd_i/J48_/g' obsf_draft.cl
sed -i'.backup' -e 's/BUTION/J46_/g' obsf_draft.cl
sed -i'.backup' -e 's/height(/J43(/g' obsf_draft.cl
sed -i'.backup' -e 's/width/J42/g' obsf_draft.cl
sed -i'.backup' -e 's/iframe/J41/g' obsf_draft.cl
sed -i'.backup' -e 's/uv/J40/g' obsf_draft.cl
sed -i'.backup' -e 's/atlas/J39/g' obsf_draft.cl
sed -i'.backup' -e 's/light/J38/g' obsf_draft.cl
sed -i'.backup' -e 's/vector/J00/g' obsf_draft.cl
sed -i'.backup' -e 's/bution/Q49_/g' obsf_draft.cl
sed -i'.backup' -e 's/fresnel/Q48_/g' obsf_draft.cl
sed -i'.backup' -e 's/reflection/Q46_/g' obsf_draft.cl
sed -i'.backup' -e 's/ld_i/Q42/g' obsf_draft.cl
sed -i'.backup' -e 's/ld_o/Q41/g' obsf_draft.cl
sed -i'.backup' -e 's/ior/Q40/g' obsf_draft.cl
sed -i'.backup' -e 's/RELATIVE_TO/Q39/g' obsf_draft.cl
sed -i'.backup' -e 's/angles/V38/g' obsf_draft.cl
sed -i'.backup' -e 's/extra/V49_/g' obsf_draft.cl
sed -i'.backup' -e 's/offset/V48_/g' obsf_draft.cl
sed -i'.backup' -e 's/HEMI/V46_/g' obsf_draft.cl
sed -i'.backup' -e 's/CONCEN/V42/g' obsf_draft.cl
sed -i'.backup' -e 's/sun/V41/g' obsf_draft.cl
sed -i'.backup' -e 's/bounce/V40/g' obsf_draft.cl
sed -i'.backup' -e 's/_index/V39/g' obsf_draft.cl
sed -i'.backup' -e 's/node/V38/g' obsf_draft.cl
sed -i'.backup' -e 's/mesh/L49_/g' obsf_draft.cl
sed -i'.backup' -e 's/top/L48_/g' obsf_draft.cl
sed -i'.backup' -e 's/sub/L46_/g' obsf_draft.cl
sed -i'.backup' -e 's/trail/L42/g' obsf_draft.cl
sed -i'.backup' -e 's/key/L41/g' obsf_draft.cl
sed -i'.backup' -e 's/leaf/L40/g' obsf_draft.cl
sed -i'.backup' -e 's/tree/L39/g' obsf_draft.cl
sed -i'.backup' -e 's/mask/L38/g' obsf_draft.cl
sed -i'.backup' -e 's/hit/W49_/g' obsf_draft.cl
sed -i'.backup' -e 's/mat_type/W48_/g' obsf_draft.cl
sed -i'.backup' -e 's/height/W46_/g' obsf_draft.cl
sed -i'.backup' -e 's/shift/W42/g' obsf_draft.cl
sed -i'.backup' -e 's/level/W41/g' obsf_draft.cl
sed -i'.backup' -e 's/angle/W40/g' obsf_draft.cl
sed -i'.backup' -e 's/rcp_dot/W39/g' obsf_draft.cl
sed -i'.backup' -e 's/_sample/W38/g' obsf_draft.cl
sed -i'.backup' -e 's/r_lo/QZ49_/g' obsf_draft.cl
sed -i'.backup' -e 's/r_hi/QZ48_/g' obsf_draft.cl
sed -i'.backup' -e 's/l_lo/QZ46_/g' obsf_draft.cl
sed -i'.backup' -e 's/l_hi/QZ42/g' obsf_draft.cl
sed -i'.backup' -e 's/ood/QZ41/g' obsf_draft.cl
sed -i'.backup' -e 's/h_t/QZ40/g' obsf_draft.cl
sed -i'.backup' -e 's/child/QZ39/g' obsf_draft.cl
sed -i'.backup' -e 's/near/QZ38/g' obsf_draft.cl
sed -i'.backup' -e 's/far/QZ398/g' obsf_draft.cl
sed -i'.backup' -e 's/basis/PZ49_/g' obsf_draft.cl
sed -i'.backup' -e 's/ndot/PZ48_/g' obsf_draft.cl
sed -i'.backup' -e 's/sample_/PZ46_/g' obsf_draft.cl
sed -i'.backup' -e 's/seeds/PZ42/g' obsf_draft.cl
sed -i'.backup' -e 's/frame/PZ40/g' obsf_draft.cl
sed -i'.backup' -e 's/n_basis/PZ39/g' obsf_draft.cl
sed -i'.backup' -e 's/ln_facet/PZ38/g' obsf_draft.cl
sed -i'.backup' -e 's/smooth/PZ398/g' obsf_draft.cl
sed -i'.backup' -e 's/tex/RQ49_/g' obsf_draft.cl
sed -i'.backup' -e 's/invert/RQ48_/g' obsf_draft.cl
sed -i'.backup' -e 's/TRACE/RQ46_/g' obsf_draft.cl
sed -i'.backup' -e 's/OCCLUSION/RQ42/g' obsf_draft.cl
sed -i'.backup' -e 's/direction/RQ40/g' obsf_draft.cl
sed -i'.backup' -e 's/cam/RQ39/g' obsf_draft.cl
sed -i'.backup' -e 's/rgb/UQR46_/g' obsf_draft.cl
sed -i'.backup' -e 's/AVG_TONEMAP/UQR42/g' obsf_draft.cl
sed -i'.backup' -e 's/anti_aliased/UQR41/g' obsf_draft.cl
sed -i'.backup' -e 's/YUV/UQR40/g' obsf_draft.cl
sed -i'.backup' -e 's/yuv/UQR39/g' obsf_draft.cl
sed -i'.backup' -e 's/neighbors/UQR398/g' obsf_draft.cl
sed -i'.backup' -e 's/top/EFJS49_/g' obsf_draft.cl
sed -i'.backup' -e 's/bottom/EFJS48_/g' obsf_draft.cl
sed -i'.backup' -e 's/left/EFJS46_/g' obsf_draft.cl
sed -i'.backup' -e 's/right/EFJS42/g' obsf_draft.cl
sed -i'.backup' -e 's/inv_sample_count/FESIEF9/g' obsf_draft.cl
sed -i'.backup' -e 's/difference/FADP46_/g' obsf_draft.cl
sed -i'.backup' -e 's/pre_clamp/FADP42/g' obsf_draft.cl
sed -i'.backup' -e 's/throughput/ZFJS49_/g' obsf_draft.cl
sed -i'.backup' -e 's/modify/EFZZS48_/g' obsf_draft.cl
sed -i'.backup' -e 's/LIGHT/EFZZ46_/g' obsf_draft.cl
sed -i'.backup' -e 's/probability/EZJS42/g' obsf_draft.cl
sed -i'.backup' -e 's/choice/FESIZZ9/g' obsf_draft.cl
sed -i'.backup' -e 's/aperture_size/FZZP46_/g' obsf_draft.cl
sed -i'.backup' -e 's/pre_clamp/FADPZZZ2/g' obsf_draft.cl
sed -i'.backup' -e 's/LightIndex/FawefADPZZZ2/g' obsf_draft.cl

rm *.backup
